app:
  name: "fastify-api"
  version: "1.0.0"
  environment: "development"
  debug: true

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database: "fastify_api"
  ssl: false

server:
  port: 3000
  host: "0.0.0.0"
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "http://localhost:3001"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    credentials: true

logging:
  level: "info"
  format: "json"
  output:
    - "console"
